name: test
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        coverage: none
        tools: composer

    - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
      run: |
        mkdir -p ~/.docker/machine/cache
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        brew install docker docker-machine
        docker-machine create --driver virtualbox default
        docker-machine env default
        eval "$(docker-machine env default)"

    - name: Install docker-compose
      run: |
            get_latest_release() {
              curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
                grep '"tag_name":' | # Get tag line
                sed -E 's/.*"([^"]+)".*/\1/' # Pluck JSON value
            }
            ARTIFACT_URL="https://github.com/docker/compose/releases/download/$(get_latest_release docker/compose)/docker-compose-$(uname -s)-$(uname -m)"
            curl -L $ARTIFACT_URL -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
