name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none
        tools: composer
        extensions: pcntl, curl, sqlite3, zip, dom, mbstring, json
    - name: Update docker
      run: |
        sudo apt purge nginx nginx-common docker docker-engine docker.io docker-ce containerd runc
        curl -fsSL https://get.docker.com/ | sudo bash
        sudo systemctl restart docker.service

    - name: Install docker-compose
      run: |
        VERSION=$(curl --silent "https://api.github.com/repos/docker/compose/releases/latest" |
          grep '"tag_name":' |
          sed -E 's/.*"([^"]+)".*/\1/'
        )
        sudo curl -L "https://github.com/docker/compose/releases/download/$VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true

